collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
  data:
    path: src/data
    icon: data_usage

paths:
  static: public
  uploads: public/doodles

_inputs:
  doodles:
    type: array
    options:
      structures: _structures.doodle
  src:
    type: image

_structures:
  doodle:
    values:
      - icon: face
        value:
          src:
          caption: